// Material SymbolsOutlined codepoints for every icon the Flutter app uses
// (lib/** `Icons.*`) — rendered through the bundled variable font
// (`MaterialSymbolsOutlined.ttf`, FILL axis flipped via fontVariations).
export const ICON_GLYPHS = {
  add: '\ue145',
  apps: '\ue5c3',
  auto_awesome: '\ue65f',
  calculate: '\uea5f',
  calendar_month: '\uebcc',
  calendar_today: '\ue935',
  chat_bubble: '\ue0cb',
  check: '\ue668',
  checklist: '\ue6b1',
  chevron_left: '\ue5cb',
  chevron_right: '\ue5cc',
  close: '\ue5cd',
  cloud_off: '\ue2c1',
  copy: '\ue14d',
  dark_mode: '\ue51c',
  dashboard: '\ue871',
  delete: '\ue92e',
  description: '\ue873',
  edit: '\uf097',
  event: '\ue878',
  expand_less: '\ue5ce',
  expand_more: '\ue5cf',
  flag: '\uf0c6',
  gpp_bad: '\uf012',
  gpp_maybe: '\uf014',
  inbox: '\ue156',
  key: '\ue73c',
  layers: '\ue53b',
  layers_clear: '\ue53c',
  light_mode: '\ue518',
  logout: '\ue9ba',
  mark_email_read: '\uf18c',
  menu_book: '\uea19',
  person: '\uf0d3',
  refresh: '\ue5d5',
  restart_alt: '\uf053',
  schedule: '\uefd6',
  school: '\ue80c',
  send: '\ue163',
  settings: '\ue8b8',
  shuffle: '\ue043',
  slideshow: '\ue41b',
  sticky_note_2: '\uf1fc',
  stop: '\ue047',
  swap_vert: '\ue8d5',
  table_chart: '\ue265',
  upload: '\uf09b',
  verified_user: '\uf013',
  visibility: '\ue8f4',
  visibility_off: '\ue8f5',
} as const;

export type IconName = keyof typeof ICON_GLYPHS;
